name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: fmt
        run: cargo fmt --all -- --check
        working-directory: ashkorix
      - name: clippy
        run: cargo clippy --all-targets -- -D warnings
        working-directory: ashkorix
      - name: test
        run: cargo test --all
        working-directory: ashkorix
